### ISSUE TITLE
LED 4 and 5 are not assigned to the correct constant

### ISSUE THREAD

**Issue by markingle** [makersmakingchange/LipSync-Classic#1]
#define LED_1 **4**                                   // LipSync LED Color1 : GREEN - digital output pin 5
#define LED_2 **5**                                   // LipSync LED Color2 : RED - digital outputpin 4

Should be .....

#define LED_1 **5**                                   // LipSync LED Color1 : GREEN - digital output pin 5
#define LED_2 **4**                                  // LipSync LED Color2 : RED - digital outputpin 4

**Comment by makersmakingchange** [comment]
Hi Mark,
I am going to close this issue as the variables are assigned correctly.
