### ISSUE TITLE
Part 26 has a 404 link

### ISSUE THREAD

**Issue by ctag** [makersmakingchange/LipSync-Classic#3]
Hi,

In the manual, the [Mouthpiece part](http://www.qosina.com/male-luer-lock-stepped-connector-11648) takes me to a "product not found" page on Qosina's website.

Would [this part](https://www.qosina.com/stepped-male-luer-lock-connector-80102) be a suitable replacement?

Thanks,
Chris

**Comment by makersmakingchange** [comment]
Hi Chris,

Thanks for catching this. You are correct about the mouthpiece. We contacted Qosina, the link you found (SKU: 80102) is the replacement for the previous one. The link is updated in Manual v.1.4.6

Thanks!
