### ISSUE TITLE
Sources for PDFs are not available in this repo?

### ISSUE THREAD

**Issue by d3r3kk** [makersmakingchange/LipSync-Classic#6]
There are a few places where I could help out in the documentation of the LipSync device. However, the LipSync repo only contains PDFs and not any editable sources (I don't own a license for any Adobe products, perhaps that is the prerequisite to updating the docs).

It would be great to have easily editable documentation in a format such as Markdown or similar, and then a process by which that input format can be transformed into other formats such as PDF.

Proposal for this might look like:

- Create a `/doc/` folder in the repo.
- Re-create the PDF content in a Markdown file each and save them in the `/doc/` folder.
- Add a script that allows people to use tools such as [Pandoc](https://pandoc.org/) to convert them to PDF.
- Consider a 'release' process that would create a zip file containing the PDF documentation.

**Comment by milador** [comment]
Excellent idea Derek @d3r3kk . @MMC-km is in charge of documentation and visual aspect so I let her perform the changes.
I started the [md files](https://github.com/makersmakingchange/LipSync/tree/develop/Documentation) in develop branch which could be a good start.

**Comment by MMC-km** [comment]
Hi @d3r3kk . I uploaded the original .docx files to the folder @milador created. The assembly manual was created with InDesign but if you want to share a list of feedback for that, I can incorporate it in our next round of manual changes. Hope that helps!
